create table users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null
);

create table job_application (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    company varchar(255),
    location varchar(255),
    description varchar(4000),
    source_url varchar(1000),
    salary varchar(255),
    job_type varchar(255),
    status varchar(255) not null,
    priority varchar(255) not null,
    created_at timestamp,
    updated_at timestamp,
    user_id bigint not null,
    constraint fk_job_application_user foreign key (user_id) references users(id),
    constraint uk_job_application_user_source unique (user_id, source_url)
);

create table application_note (
    id bigint generated by default as identity primary key,
    text varchar(2000) not null,
    created_at timestamp,
    application_id bigint not null,
    constraint fk_application_note_application foreign key (application_id) references job_application(id)
);

create index idx_job_application_user_status on job_application(user_id, status);
create index idx_job_application_created_at on job_application(created_at);
create index idx_application_note_application on application_note(application_id);
